<?
require("includes/funcoes_layout.php");

$modo = $_REQUEST["modo"];
$DOMICILIO = $_REQUEST["DOMICILIO"];
$PESSOA = $_REQUEST["PESSOA"];
$COD_QUALIF_ESCOLAR_PESSOA = $_REQUEST["COD_QUALIF_ESCOLAR_PESSOA"];
$COD_GRAU_INSTRUCAO_PESSOA = $_REQUEST["COD_GRAU_INSTRUCAO_PESSOA"];
$NUM_SERIE_ESCOLAR_PESSOA = $_REQUEST["NUM_SERIE_ESCOLAR_PESSOA"];
$NOM_ESCOLA_PESSOA = $_REQUEST["NOM_ESCOLA_PESSOA"];
$COD_CENSO_INEP_PESSOA = $_REQUEST["COD_CENSO_INEP_PESSOA"];
$SIT_MERCADO_TRAB_PESSOA = $_REQUEST["SIT_MERCADO_TRAB_PESSOA"];
$NOM_EMPRESA_TRAB_PESSOA = $_REQUEST["NOM_EMPRESA_TRAB_PESSOA"];
$NUM_CNPJ_EMPRESA_PESSOA = $_REQUEST["NUM_CNPJ_EMPRESA_PESSOA"];
$DTA_ADMIS_EMPRESA_PESSOA = $_REQUEST["DTA_ADMIS_EMPRESA_PESSOA"];
$NOM_OCUPACAO_EMPRESA_PESSOA = $_REQUEST["NOM_OCUPACAO_EMPRESA_PESSOA"];
$VAL_REMUNER_EMPREGO_PESSOA = $_REQUEST["VAL_REMUNER_EMPREGO_PESSOA"];
$VAL_RENDA_APOSENT_PESSOA = $_REQUEST["VAL_RENDA_APOSENT_PESSOA"];
$VAL_RENDA_SEGURO_DESEMP_PESSOA = $_REQUEST["VAL_RENDA_SEGURO_DESEMP_PESSOA"];
$VAL_RENDA_PENSAO_ALIMEN_PESSOA = $_REQUEST["VAL_RENDA_PENSAO_ALIMEN_PESSOA"];
$VAL_OUTRAS_RENDAS_PESSOA = $_REQUEST["VAL_OUTRAS_RENDAS_PESSOA"];

$VAL_REMUNER_EMPREGO_PESSOA = str_replace(".","",$VAL_REMUNER_EMPREGO_PESSOA);
$VAL_RENDA_APOSENT_PESSOA = str_replace(".","",$VAL_RENDA_APOSENT_PESSOA);
$VAL_RENDA_SEGURO_DESEMP_PESSOA = str_replace(".","",$VAL_RENDA_SEGURO_DESEMP_PESSOA);
$VAL_RENDA_PENSAO_ALIMEN_PESSOA = str_replace(".","",$VAL_RENDA_PENSAO_ALIMEN_PESSOA);
$VAL_OUTRAS_RENDAS_PESSOA = str_replace(".","",$VAL_OUTRAS_RENDAS_PESSOA);

$VAL_REMUNER_EMPREGO_PESSOA = str_replace(",",".",$VAL_REMUNER_EMPREGO_PESSOA);
$VAL_RENDA_APOSENT_PESSOA = str_replace(",",".",$VAL_RENDA_APOSENT_PESSOA);
$VAL_RENDA_SEGURO_DESEMP_PESSOA = str_replace(",",".",$VAL_RENDA_SEGURO_DESEMP_PESSOA);
$VAL_RENDA_PENSAO_ALIMEN_PESSOA = str_replace(",",".",$VAL_RENDA_PENSAO_ALIMEN_PESSOA);
$VAL_OUTRAS_RENDAS_PESSOA = str_replace(",",".",$VAL_OUTRAS_RENDAS_PESSOA);

$DTA_ADMIS_EMPRESA_PESSOA = split("/", $DTA_ADMIS_EMPRESA_PESSOA);
$DTA_ADMIS_EMPRESA_PESSOA = $DTA_ADMIS_EMPRESA_PESSOA[2] . "-" . $DTA_ADMIS_EMPRESA_PESSOA[1] . "-" . $DTA_ADMIS_EMPRESA_PESSOA[0];


require("includes/conectar_mysql.php");

if($modo == "add"){
	/*$query = "SELECT DOMICILIO FROM domicilio_1 WHERE NOM_LOGRADOURO_DOMIC='" . $NOM_LOGRADOURO_DOMIC . "' AND NUM_RESIDENCIA_DOMIC";
	$result = mysql_query($query) or tela_erro("Erro de conexão ao banco de dados: " . mysql_error());
	if(mysql_num_rows($result)>0) tela_erro("Já existe um programa social com este código. Clique no botão VOLTAR e informe outro.");
	else{*/
	$query = "INSERT INTO pessoa_3 (PESSOA, COD_QUALIF_ESCOLAR_PESSOA, COD_GRAU_INSTRUCAO_PESSOA, NUM_SERIE_ESCOLAR_PESSOA, NOM_ESCOLA_PESSOA, COD_CENSO_INEP_PESSOA, SIT_MERCADO_TRAB_PESSOA, NOM_EMPRESA_TRAB_PESSOA, NUM_CNPJ_EMPRESA_PESSOA, DTA_ADMIS_EMPRESA_PESSOA, NOM_OCUPACAO_EMPRESA_PESSOA, VAL_REMUNER_EMPREGO_PESSOA, VAL_RENDA_APOSENT_PESSOA, VAL_RENDA_SEGURO_DESEMP_PESSOA, VAL_RENDA_PENSAO_ALIMEN_PESSOA, VAL_OUTRAS_RENDAS_PESSOA) VALUES ";
	$query .= "('" . $PESSOA . "',";
	$query .= "'" . $COD_QUALIF_ESCOLAR_PESSOA . "',";
	$query .= "'" . $COD_GRAU_INSTRUCAO_PESSOA . "',";
	$query .= "'" . $NUM_SERIE_ESCOLAR_PESSOA . "',";
	$query .= "'" . $NOM_ESCOLA_PESSOA . "',";
	$query .= "'" . $COD_CENSO_INEP_PESSOA . "',";
	$query .= "'" . $SIT_MERCADO_TRAB_PESSOA . "',";
	$query .= "'" . $NOM_EMPRESA_TRAB_PESSOA . "',";
	$query .= "'" . $NUM_CNPJ_EMPRESA_PESSOA . "',";
	$query .= "'" . $DTA_ADMIS_EMPRESA_PESSOA . "',";
	$query .= "'" . $NOM_OCUPACAO_EMPRESA_PESSOA . "',";
	$query .= "'" . $VAL_REMUNER_EMPREGO_PESSOA . "',";
	$query .= "'" . $VAL_RENDA_APOSENT_PESSOA . "',";
	$query .= "'" . $VAL_RENDA_SEGURO_DESEMP_PESSOA . "',";
	$query .= "'" . $VAL_RENDA_PENSAO_ALIMEN_PESSOA . "',";
	$query .= "'" . $VAL_OUTRAS_RENDAS_PESSOA . "')";
	//}
}
if($modo == "update"){
	$query = "UPDATE pessoa_3 SET ";
	$query .= "COD_QUALIF_ESCOLAR_PESSOA='" . $COD_QUALIF_ESCOLAR_PESSOA . "',";
	$query .= "COD_GRAU_INSTRUCAO_PESSOA='" . $COD_GRAU_INSTRUCAO_PESSOA . "',";
	$query .= "NUM_SERIE_ESCOLAR_PESSOA='" . $NUM_SERIE_ESCOLAR_PESSOA . "',";
	$query .= "NOM_ESCOLA_PESSOA='" . $NOM_ESCOLA_PESSOA . "',";
	$query .= "COD_CENSO_INEP_PESSOA='" . $COD_CENSO_INEP_PESSOA . "',";
	$query .= "SIT_MERCADO_TRAB_PESSOA='" . $SIT_MERCADO_TRAB_PESSOA . "',";
	$query .= "NOM_EMPRESA_TRAB_PESSOA='" . $NOM_EMPRESA_TRAB_PESSOA . "',";
	$query .= "NUM_CNPJ_EMPRESA_PESSOA='" . $NUM_CNPJ_EMPRESA_PESSOA . "',";
	$query .= "DTA_ADMIS_EMPRESA_PESSOA='" . $DTA_ADMIS_EMPRESA_PESSOA . "',";
	$query .= "NOM_OCUPACAO_EMPRESA_PESSOA='" . $NOM_OCUPACAO_EMPRESA_PESSOA . "',";
	$query .= "VAL_REMUNER_EMPREGO_PESSOA='" . $VAL_REMUNER_EMPREGO_PESSOA . "',";
	$query .= "VAL_RENDA_APOSENT_PESSOA='" . $VAL_RENDA_APOSENT_PESSOA . "',";
	$query .= "VAL_RENDA_SEGURO_DESEMP_PESSOA='" . $VAL_RENDA_SEGURO_DESEMP_PESSOA . "',";
	$query .= "VAL_RENDA_PENSAO_ALIMEN_PESSOA='" . $VAL_RENDA_PENSAO_ALIMEN_PESSOA . "',";
	$query .= "VAL_OUTRAS_RENDAS_PESSOA='" . $VAL_OUTRAS_RENDAS_PESSOA . "'";
	$query .= " WHERE PESSOA=" . $PESSOA;
}
$result = mysql_query($query) or tela_erro("Erro ao atualizar registros no Banco de dados: " . mysql_error() . $query);
if($result) header("Location: form_usuario_familia_8.php?DOMICILIO=" . $DOMICILIO . "&PESSOA=" . $PESSOA);

require("includes/desconectar_mysql.php");
?>